### ISSUE TITLE
Managed security logout does not always work

### ISSUE THREAD

**Issue by peholmst** [peholmst/vaadin4spring#253]
Sometimes, the logout mechanism in the managed security demo application does not log the user out. And sometimes, it does. Need to investigate this and fix it.

**Comment by shinchillahh** [comment]
After doing a login, vaadinSecurity.isAuthenticated() inside the init method of the UI returnes true, so the mainview is shown. But when i call the method in another view it returnes false... It seems that the user isn't logged in...

**Comment by shinchillahh** [comment]
In my case the logout doesn't work because the user isn't logged in. vaadinSecurity.isAuthenticated() returnes false altough the user did a log in... So 
1. vaadinSecurity.login("user", "pw") is called
2. the event SuccessfulLoginEvent is published
3. eventbuslistener method onLogin is called
-> here vaadinSecurity.getAuthentication().getName() returnes the correct username of the login!
4. showMainScreen() is called
-> inside the new view the -injected- vaadinSecurity.isAuthenticated() returnes true/false randomly

**Comment by peholmst** [comment]
I can't reproduce this problem any more with the latest Vaadin version. Also, everything seems to work with `@PreserveOnRefresh` as well, so I'm closing this ticket. If the problem reappears, I'll open a new one.
