### ISSUE TITLE
Set session timeout using VaadinSharedSecurity

### ISSUE THREAD

**Issue by toplac** [peholmst/vaadin4spring#276]
Hello,

we are using Spring Boot & VaadinSharedSecurity, and everyhting is working so far for us.
The only problem we are having, ist setting the the automaitc sesion timeout, meaning the session is valid unti the user logs out 

server.session.timeout=120

But nothing happens.
Is there another solution?

**Comment by peholmst** [comment]
Have you checked that the Vaadin heartbeat signals are not keeping the session alive?

**Comment by knacht** [comment]
Thanks for the hint. I didnt have time to check the heartbet yet. 
Does vaadin4spring take the parameter into consideration?

**Comment by peholmst** [comment]
I just discovered something. It appears that when the Vaadin session expires, the HTTP session will still remain alive for the duration of the session timeout. I think the reason is that the heartbeat signals still keep the HTTP session alive, even though Vaadin will expire its own session if no other requests have been received. Once the Vaadin session expires, the heartbeats stop and eventually, the HTTP session will also expire. I have to see what we can do about this.

**Comment by toplac** [comment]
Since I am not working on this project anymore, I am closing this issue for now. 
Feel free top open again, if needed
