### ISSUE TITLE
Security: redirect to "login" from address bar causes Access Denied error (HTTP 403)

### ISSUE THREAD

**Issue by hectorlicea** [peholmst/vaadin4spring#291]
I am running the Shared Security sample. I enter correctly to the application (localhost:8080/login). When I logon, the application redirects to localhost:8080 and I can access to the options. If in the address bar, I add "/login" to "localhost:8080" (localhost:8080/login), the application crash. How can I fix this?

**Comment by Horuss** [comment]
See security configuration in Application class:
`http.authorizeRequests().antMatchers("/login/**").anonymous()`
It allows only anonymous users to see login page - that's why you get 403. If you wish to allow users to see this view (and probably behave differently in that case), use permitAll() instead of anonymous()

**Comment by hectorlicea** [comment]
Thanks for the help. 
It works.
