### ISSUE TITLE
Create a guide

### ISSUE THREAD

**Issue by peholmst** [peholmst/vaadin4spring#6]
Create a guide / tutorial for getting started with Spring Boot and Vaadin.

**Comment by GJRTimmer** [comment]
This issue may be a great example to put on the project wiki ?

**Comment by peholmst** [comment]
The idea was/is to get it published here: https://spring.io/guides

**Comment by GJRTimmer** [comment]
Great idea, however I think we would have a real challenge getting our guide there, because only guides that are directly linked to the spring-project itself are published there. In order to get our guide published we would need to get the vaadin4spring project adapted within the spring-project as a module. 

It that your ultimate goal ?

**Comment by peholmst** [comment]
That remains to be seen... In the mean time, we can write the guide in the wiki.

**Comment by peholmst** [comment]
Vaadin + Spring guides are starting to show up, so I'm closing this (e.g. https://spring.io/guides/gs/crud-with-vaadin/)
